COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:ONOS_YANG',
#    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//protocols/netconf/ctl:onos-protocols-netconf-ctl',
    '//models/tiessemanager:onos-models-tiessemanager',
    '//lib:org.apache.karaf.shell.console',
    '//incubator/api:onos-incubator-api',
] + YANG_TOOLS

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//utils/osgi:onlab-osgi-tests',
    '//incubator/net:onos-incubator-net'
]

APPS = [
    'org.onosproject.yang',
#     'org.onosproject.yang-gui',
    'org.onosproject.config',
    'org.onosproject.netconf',
    'org.onosproject.netconfsb',
    'org.onosproject.drivers.netconf',
    'org.onosproject.models.tiessemanager'
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
#    resources_root = 'src/main/resources',
#    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.tiessemanager',
    title = 'tiessemanager app',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'ONOS tiessemanager YANG application.',
    required_apps = APPS,
)
