COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//models/MyTestDriver:onos-models-MyTestDriver',
] + YANG_TOOLS

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests'
]

APPS = [
    'org.onosproject.yang',
#     'org.onosproject.yang-gui',
    'org.onosproject.models.MyTestDriver'
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS
)

onos_app (
    app_name = 'org.onosproject.drivers.MyTestDriver',
    title = 'MyTestDriver sample device driver',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS MyTestDriver device drivers application.',
    required_apps = APPS,
)
